new_project/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Post;
use App\Models\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/insert/user/{id}/post' , function ($id){

    $post = new \App\Models\Post();
    $post->title = 'Business man ';
    $post->post_image = 'https://i.ytimg.com/vi/bfXZ1io4d3k/maxresdefault.jpg';
    $post->content = 'Garments business international brand pandu  ';

    $user = \App\Models\User::find($id);

    $user->posts()->save($post);
});

Route::get('/logout' , function (){

    return view('welcome');


})->name('logout');
Route::get('/dashboard', function () {

    return view('dashboard' );
})->middleware(['auth'])->name('dashboard');

Route::get('/', [ App\Http\Controllers\HomeController::class , 'show'])->name('home');

Route::get('/admin', 'App\Http\Controllers\AdminController@index')->name('admin');

Route::get('/post/{id}', 'App\Http\Controllers\PostController@show')->name('post');

Route::get('/admin/post/create', 'App\Http\Controllers\PostController@create')->name('posts.create');

Route::post('/admin/post/save', 'App\Http\Controllers\PostController@store')->name('posts.store');

Route::get('/show/posts', 'App\Http\Controllers\PostController@index')->name('posts.show');

Route::delete('/posts/{id}/destroy', 'App\Http\Controllers\PostController@delete')->name('posts.delete');

Route::get('/posts/{id}/show', 'App\Http\Controllers\PostController@edit')->name('posts.edit');

Route::patch('/posts/{id}/update', 'App\Http\Controllers\PostController@update')->name('posts.update');

Route::get('/admin/{id}/profile', 'App\Http\Controllers\UserController@show')->name('admin.profile.show');

Route::patch('/admin/profile/{id}/update', 'App\Http\Controllers\UserController@update')->name('admin.profile.update');



Route::delete('delete/user/{id}' , 'App\Http\Controllers\AdminController@delete')->name('admin.user.delete');
require __DIR__.'/auth.php';


Route::middleware('role:Admin')->group(function (){

    Route::get('show/all/users' , 'App\Http\Controllers\AdminController@show')->name('admin.users.show');

    Route::get('admin/roles/create' , 'App\Http\Controllers\RoleController@create')->name('roles.create');

    Route::post('admin/roles/store' , 'App\Http\Controllers\RoleController@store')->name('roles.store');

    Route::get('/assign/user/{id}/role', 'App\Http\Controllers\RoleController@show')->name('assign.roles');

    Route::Patch('attach/user/{id}/role' , 'App\Http\Controllers\RoleController@attach')->name('admin.attach.role');
    Route::Patch('detach/user/{id}/role' , 'App\Http\Controllers\RoleController@detach')->name('admin.detach.role');

    Route::get('edit/role/{id}' , 'App\Http\Controllers\RoleController@edit')->name('admin.roles.edit');

    Route::Patch('update/role/{id}' , 'App\Http\Controllers\RoleController@update')->name('admin.roles.update');
    Route::delete('delete/role/{id}' , 'App\Http\Controllers\RoleController@delete')->name('admin.role.delete');

    Route::get('assign/permission/role/{id}' , 'App\Http\Controllers\PermissionController@show')->name('assign.permissions.show');

    Route::patch('attach/role/{id}/toPermission' , 'App\Http\Controllers\PermissionController@attach')->name('attach.role.to.permission');
    Route::patch('detach/role/{id}/toPermission' , 'App\Http\Controllers\PermissionController@detach')->name('detach.role.to.permission');

    Route::get('create.permissions' , 'App\Http\Controllers\PermissionController@create')->name('admin.permissions.create');
    Route::post('store.permissions' , 'App\Http\Controllers\PermissionController@store')->name('permission.store');
    Route::delete('delete.permissions/{id}' , 'App\Http\Controllers\PermissionController@delete')->name('delete.permission');
    Route::get('edit/permission/{id}' , 'App\Http\Controllers\PermissionController@edit')->name('permission.edit');
    Route::patch('update/permission/{id}' , 'App\Http\Controllers\PermissionController@update')->name('admin.permissions.update');
});

new_project/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts(){

        return $this->hasMany('App\Models\Post');

    }

    public function getAvatarAttribute($value){

        //********* For online images ***********************\\
        if( str_contains($value , 'https://') == true  || str_contains($value , 'http://') == true )
        {
        return $value;
        }

        //************* For Local Images ***********************\\

        return asset('storage/'.$value);
    }

    public function roles(){

        return $this->belongsToMany(Role::class);

    }

    public function permissions(){

        return $this->belongsToMany(Permission::class);

    }

    public function userIsAdmin($role_name){

        foreach ($this->roles as $role){
            if($role->name === $role_name)
            {
                return true;
            }
        }

        return false;

    }

}

new_project/resources/views/admin/admin-profile.blade.php
<x-admin-master>

    @section('content')

        <h3>Admin's profile</h3>

        <form method="Post" action="{{route('admin.profile.update' , $user->id)}}" enctype="multipart/form-data">
            @csrf
            @method('PATCH')

            <div class="container py-4">

                <div class="img-profile">

                    <img height="100px" src="{{$user->avatar}}" alt="profile picture">

                </div>

                <div class="mb-3">
                    <input class="form-control-file" type="file" name="avatar" >

                </div>

                <div class="mb-3">
                    <label class="form-label" for="name">Name</label>
                    <input class="form-control" type="text" name="name" id="name" value="{{$user->name}}">

                    @error('name')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror

                </div>

                <div class="mb-3">
                    <label class="form-label" for="email">Email</label>
                    <input @error('email') is_invalid @enderror class="form-control" type="text" name="email" id="email" value="{{$user->email}}">
                    @error('email')
                    <div class="is_invalid alert-danger">{{$message}}</div>
                    @enderror
                </div>

                <div class="mb-3">
                    <label class="form-label" for="password">Password</label>
                    <input class="form-control" type="password" name="password" id="password" >
                </div>

                <div class="mb-3">
                    <label class="form-label" for="confirm-password">Confirm Password</label>
                    <input class="form-control" type="password" name="confirm_password" id="confirm-password" >
                </div>

                <div class="d-grid">
                    <button class="btn btn-primary btn-lg" type="submit">Update</button>
                </div>
            </div>



        </form>

    @endsection



</x-admin-master>

new_project/resources/views/admin/index.blade.php
<x-admin-master :users="$users">

    @section('content')
        @if(session('updated'))
            <div classs="container p-5">
                <div class="row no-gutters">
                    <div class="col-lg-5 col-md-12">
                        <div class="alert alert-success fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="True">&times;</span>
                            </button>
                            <h4 class="alert-heading">Success</h4>
                            <p>The profile has been successfully updated</p>
                        </div>
                    </div>
                </div>
            </div>
        @endif

         <h1 class="h3 mb-4 text-gray-800">{{$users->name}}</h1>
    @endsection

        <x-admin-profile-master :users="$users"></x-admin-profile-master>

</x-admin-master>